version: '3'
services:
  apifake:
    build: ./apifake
    ports:
      - 3000:3000
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - 1080:1080
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: x
    volumes:
      - ./sql:/tmp/sql/
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  logstash:
    image: "docker.elastic.co/logstash/logstash:7.1.0"
    depends_on:
      - mysql
      - mailcatcher
    volumes:
      - ./pipeline:/usr/share/logstash/pipeline/
      - ./sample_csv:/tmp/sample_csv
      - ./connector:/tmp/connector
    links:
      - mysql
      - redis
      - elasticsearch
      - mailcatcher
    ports:
      - "5044:5044"
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.1.0"
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - cluster.routing.allocation.disk.threshold_enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    user: 'elasticsearch'
  kibana:
    image: "docker.elastic.co/kibana/kibana:7.1.0"
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    links:
      - elasticsearch
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.1.0
    user: root
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    links:
      - logstash
    command: filebeat -e -strict.perms=false
    depends_on:
      - logstash
  fakelog:
    build: ./fakelog
    labels:
      - co.elastic.logs/module=apache2
      - co.elastic.logs/fileset.stdout=access
      - co.elastic.logs/fileset.stderr=error
    depends_on:
      - logstash
      - filebeat
      - elasticsearch
      - kibana