version: '3'
services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: x
      MYSQL_DATABASE: user
    volumes:
      - ./sql:/tmp/sql/
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  logstash:
    image: "docker.elastic.co/logstash/logstash:7.1.0"
    volumes:
      - ./pipeline:/usr/share/logstash/pipeline/
      - ./sample_csv:/tmp/sample_csv
      - ./connector:/tmp/connector
    links:
      - mysql
      - redis
      - elasticsearch
    ports:
      - "5044:5044"
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.1.0"
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - cluster.routing.allocation.disk.threshold_enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    user: 'elasticsearch'
  kibana:
    image: "docker.elastic.co/kibana/kibana:7.1.0"
    ports:
      - "5601:5601"
    links:
      - elasticsearch